# Site settings
title: Sass Compatibility Table
email: ''
description: > # this means to ignore newlines until "baseurl:"
  Sass Compatibility Table aims at finding and reporting Sass differences between different engines, especially Ruby Sass and LibSass.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hugogiraudel.github.com/sass-compatibility" # the base hostname & protocol for your site
twitter_username: HugoGiraudel
github_username:  HugoGiraudel

# Build settings
markdown: kramdown
